/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

BOOL __stdcall DllEntryPoint(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved);
// void __usercall sub_107705E3(int a1@<eax>, int _EBX@<ebx>, int (**a3)(void)@<ebp>, int a4@<edi>, int a5@<esi>);
int nullsub_6(void); // weak
void __cdecl sub_10791EAA(int a1, int a2);
void __cdecl sub_1079FAD4(int a1, int a2, int a3, int a4, int a5);
void __cdecl sub_107AC3DD(int a1);
void __cdecl sub_107B0419(int a1, int a2);
int __cdecl nullsub_10(_DWORD); // weak
void __cdecl sub_107D2CF7(int a1, int a2, int a3);
void __cdecl sub_107D897F(int a1, int a2);
// void __usercall sub_107DBB5B(int a1@<eax>, int a2@<edx>, int a3@<ecx>, int a4);
int __cdecl nullsub_8(_DWORD); // weak
// int __usercall sub_107F28C8@<eax>(char a1@<al>, int a2@<ebx>, int (**a3)(void)@<ebp>);
// void __usercall sub_107FD2C1(int a1@<edx>, int a2@<ebp>, int a3@<edi>);
// void __usercall sub_108140F9(__int16 a1@<di>, int a2);
void __cdecl sub_10815F1D(int a1, int a2, int a3, int a4, int a5);
void __cdecl sub_1082DA24(int a1, int a2, int a3);
void __cdecl sub_10833A6D(int a1, int a2);
int nullsub_7(void); // weak
int nullsub_112(void); // weak
// void __usercall sub_1088D22E(int a1@<edi>, int a2);
// void __usercall sub_10892AC7(__int16 _AX@<ax>, int a2@<edx>, char a3@<cl>, int a4@<ebx>, int (**a5)(void)@<ebp>);
// int __usercall sub_108DCB14@<eax>(int a1@<ebx>, unsigned int a2@<ebp>, _DWORD *a3@<edi>, int a4@<esi>, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26, int a27, char a28);
// int __usercall sub_108DEEB4@<eax>(int a1@<ebx>, int a2@<esi>, HMODULE hModule, unsigned __int8 *lpProcName, char a5);
int nullsub_5(void); // weak
// int __usercall sub_108E66DC@<eax>(_BYTE *a1@<eax>, char *a2@<ecx>, __int16 a3@<bx>, int a4@<ebp>);
void sub_10CA2D4B();
// void __usercall sub_10CA5B0A(int _EAX@<eax>, int a2@<edx>, char _CL@<cl>, int _EBX@<ebx>, int a5@<edi>, int (**a6)(void)@<esi>);
// int __usercall sub_10CA8E63@<eax>(unsigned __int8 *_EAX@<eax>, unsigned __int8 *_ECX@<ecx>, __int16 _SI@<si>, char a4);
int __cdecl nullsub_11(_DWORD); // weak
// int __usercall sub_10CD7B27@<eax>(int a1@<ebx>, int a2@<ebp>, int a3@<edi>, unsigned int *a4@<esi>);
// void __usercall sub_10CD7C66(int _EAX@<eax>, int _EDX@<edx>, int a3@<ecx>, int a4@<ebp>, int _EDI@<edi>, int _ESI@<esi>, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26);
int __cdecl nullsub_9(_DWORD); // weak
// void __usercall sub_10E32BB8(char a1@<cl>, int _EBX@<ebx>, int a3@<edi>, unsigned int a4);
// void __usercall sub_10E557A8(__int16 a1@<di>, int a2);
int nullsub_113(void); // weak
void sub_10E6ED14();
void sub_10E73280();

//-------------------------------------------------------------------------
// Data declarations

// extern HMODULE (__stdcall *LoadLibraryA)(LPCSTR lpLibFileName);
// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);


//----- (10769926) --------------------------------------------------------
#error "1076992B: call analysis failed (funcsize=73)"

//----- (107705E3) --------------------------------------------------------
void __usercall sub_107705E3(int a1@<eax>, int _EBX@<ebx>, int (**a3)(void)@<ebp>, int a4@<edi>, int a5@<esi>)
{
  int v6; // ebx
  int v7; // [esp-Ch] [ebp-Ch]

  LOBYTE(_EBX) = a1 ^ _EBX;
  v7 = _EBX;
  __asm { rcl     bh, 2Dh }
  v6 = a1;
  for ( *(a3 - 1) = (int (*)(void))&a3[a1]; v6; --v6 )
    ;
  *(_DWORD *)*(a3 - 1) = (*a3)();
  __asm { retn }
}

//----- (10791EAA) --------------------------------------------------------
void __cdecl sub_10791EAA(int a1, int a2)
{
  sub_107B0419(a1, a2);
}

//----- (1079FAD4) --------------------------------------------------------
void __cdecl sub_1079FAD4(int a1, int a2, int a3, int a4, int a5)
{
  int v5; // esi

  v5 = __ROR4__((a5 ^ 0x64217022) - 1, 3) - 585783636;
  __asm { jmp     edi }
}

//----- (107AC3DD) --------------------------------------------------------
void __cdecl sub_107AC3DD(int a1)
{
  int v1; // ebx

  __readeflags();
  v1 = __ROL4__(_byteswap_ulong((a1 + 1) ^ 0x304C6D34), 3);
  __asm { retn }
}

//----- (107B0419) --------------------------------------------------------
void __cdecl sub_107B0419(int a1, int a2)
{
  __readeflags();
  sub_10CA2D4B();
}

//----- (107D2CF7) --------------------------------------------------------
void __cdecl sub_107D2CF7(int a1, int a2, int a3)
{
  __readeflags();
  sub_1082DA24(a1, a2, a3);
}

//----- (107D897F) --------------------------------------------------------
void __cdecl sub_107D897F(int a1, int a2)
{
  sub_10833A6D(a1, a2);
}

//----- (107DBB5B) --------------------------------------------------------
void __usercall sub_107DBB5B(int a1@<eax>, int a2@<edx>, int a3@<ecx>, int a4)
{
  int v4; // ebx
  unsigned int v6; // kr00_4
  int v7; // [esp-24h] [ebp-24h]
  int v8; // [esp-20h] [ebp-20h]
  int v9; // [esp-10h] [ebp-10h]
  unsigned int v10; // [esp-8h] [ebp-8h]
  int v11; // [esp-4h] [ebp-4h]

  v11 = a3;
  _CX = a1;
  v6 = __readeflags();
  v10 = v6;
  __asm { rcl     ch, cl }
  v9 = a1;
  HIBYTE(_CX) = BYTE1(a2);
  __asm { rcl     ch, 56h }
  v8 = a2;
  v7 = 0;
  v4 = ~(~(__ROR4__(a4, 1) - 1661093586) ^ 0xEC82545);
  __asm { retn }
}

//----- (107F28C8) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __usercall sub_107F28C8@<eax>(char a1@<al>, int a2@<ebx>, int (**a3)(void)@<ebp>)
{
  unsigned int v7; // [esp-8h] [ebp-Ch]
  int v8; // [esp-4h] [ebp-8h]
  int v9; // [esp+0h] [ebp-4h]

  if ( a1 )
  {
    do
      v7 = (unsigned int)a3[a2--];
    while ( a2 );
  }
  *(_DWORD *)*(a3 - 1) = (*a3)();
  _AH = 78;
  __asm { rcr     ah, cl }
  return ((int (*)(void))(_byteswap_ulong(__ROL4__(~(v7 ^ *(_DWORD *)(v9 - 4)), 1) + 1) + v8))();
}
// 107B5F11: positive sp value 4 has been found
// 1085DD9E: variable 'v7' is possibly undefined
// 1085DD91: variable 'v9' is possibly undefined
// 107B5F1A: variable 'v8' is possibly undefined

//----- (107FD2C1) --------------------------------------------------------
void __usercall sub_107FD2C1(int a1@<edx>, int a2@<ebp>, int a3@<edi>)
{
  int v4; // [esp-C0h] [ebp-C0h] BYREF

  _EDI = (unsigned int)&v4 ^ a3;
  LOWORD(_EDI) = (__int16)_EDI >> 11;
  __asm
  {
    rcl     edi, 98h
    retn
  }
}

//----- (108140F9) --------------------------------------------------------
void __usercall sub_108140F9(__int16 a1@<di>, int a2)
{
  __readeflags();
  _DX = a1 ^ 0xF0;
  __asm { rcr     dx, 78h }
  JUMPOUT(0x1076F6C3);
}
// 1081415B: control flows out of bounds to 1076F6C3
// 1076F5A8: using guessed type int dword_1076F5A8[75];

//----- (10815F1D) --------------------------------------------------------
void __cdecl sub_10815F1D(int a1, int a2, int a3, int a4, int a5)
{
  __getcallerseflags();
  sub_1079FAD4(a1, a2, a3, a4, a5);
}

//----- (1082DA24) --------------------------------------------------------
void __cdecl sub_1082DA24(int a1, int a2, int a3)
{
  int v3; // ebp

  v3 = __ROR4__(a3 + 1, 3);
  __asm { jmp     esi }
}

//----- (10833A6D) --------------------------------------------------------
void __cdecl sub_10833A6D(int a1, int a2)
{
  __readeflags();
  __asm { jmp     esi }
}

//----- (1088D22E) --------------------------------------------------------
void __usercall sub_1088D22E(int a1@<edi>, int a2)
{
  __readeflags();
  sub_107FD2C1(0, a2, a1);
}

//----- (10892AC7) --------------------------------------------------------
void __usercall sub_10892AC7(__int16 _AX@<ax>, int a2@<edx>, char a3@<cl>, int a4@<ebx>, int (**a5)(void)@<ebp>)
{
  int (*v8)(void); // [esp-8h] [ebp-10h]
  int v9; // [esp-4h] [ebp-Ch]

  HIBYTE(_AX) >>= a3;
  LOBYTE(a4) = a2 ^ a4;
  __asm { rcl     ax, 95h }
  v9 = a4;
  _EBX = a2;
  for ( *(a5 - 1) = (int (*)(void))&a5[a2]; _EBX; --_EBX )
    v8 = a5[_EBX];
  __asm { rcr     bh, 94h }
  *(_DWORD *)*(a5 - 1) = (*a5)();
  __asm { retn }
}
// 10CD26EF: variable 'v8' is possibly undefined

//----- (108DCB14) --------------------------------------------------------
int __usercall sub_108DCB14@<eax>(
        int a1@<ebx>,
        unsigned int a2@<ebp>,
        _DWORD *a3@<edi>,
        int a4@<esi>,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        char a28)
{
  int (*v28)(void); // esi
  unsigned int v29; // kr00_4
  int (*v31)(void); // [esp-8h] [ebp-8h]
  void *retaddr; // [esp+0h] [ebp+0h] BYREF

  v28 = (int (*)(void))(_byteswap_ulong(~__ROR4__((a1 ^ *a3) + 216084522, 1)) + a4);
  if ( a2 <= (unsigned int)&a28 )
  {
    v31 = v28;
    v29 = __readeflags();
    qmemcpy((void *)(((a2 - 128) & 0xFFFFFFFC) - 64), &retaddr, 0x40u);
    __writeeflags(v29);
    v28 = v31;
  }
  return v28();
}

//----- (108DEEB4) --------------------------------------------------------
int __usercall sub_108DEEB4@<eax>(int a1@<ebx>, int a2@<esi>, HMODULE hModule, unsigned __int8 *lpProcName, char a5)
{
  HMODULE ModuleHandleA; // eax
  int v7; // edx
  unsigned int v8; // esi
  CHAR *v11; // ebx
  char v12; // dl
  unsigned int v13; // edx
  unsigned __int8 *v14; // ecx
  _BYTE *v15; // eax
  int v16; // eax
  _DWORD *v18; // edx
  int v19; // ebx
  char *v20; // edx
  int v21; // esi
  char v22; // cl
  char *v23; // esi
  const CHAR *v24; // edx
  unsigned int v27; // edx
  HMODULE v29; // edi
  char *v31; // edx
  unsigned int v32; // eax
  char v33; // cl
  unsigned int v35; // ecx
  int v36; // ebx
  CHAR v37; // al
  unsigned int v38; // ecx
  int v39; // [esp-8h] [ebp-120h]
  int v40; // [esp-4h] [ebp-11Ch]
  CHAR LibFileName[260]; // [esp+4h] [ebp-114h] BYREF
  int v42; // [esp+108h] [ebp-10h]
  char *v43; // [esp+10Ch] [ebp-Ch]
  unsigned int v44; // [esp+110h] [ebp-8h]
  unsigned int v45; // [esp+114h] [ebp-4h]
  HMODULE hModulea; // [esp+120h] [ebp+8h]

  v29 = hModule;
  if ( !hModule )
    return nullsub_6();
  v14 = lpProcName;
  if ( !lpProcName )
    return nullsub_6();
  if ( *(_WORD *)hModule != 23117 )
    return nullsub_6();
  v18 = (_DWORD *)((char *)hModule + *((_DWORD *)hModule + 15));
  if ( *v18 != 17744 )
    return nullsub_6();
  v32 = v18[30];
  v45 = v32;
  if ( !v32 )
    return nullsub_6();
  v7 = v18[31];
  v40 = a1;
  v39 = a2;
  v8 = -1;
  v42 = v7;
  v44 = -1;
  if ( (unsigned int)lpProcName > 0xFFFF )
  {
    v36 = *(_DWORD *)((char *)hModule + v32 + 24);
    if ( v36 )
    {
      v19 = v36 - 1;
      v20 = (char *)hModule + *(_DWORD *)((char *)hModule + v32 + 32);
      hModule = 0;
      v43 = (char *)v29 + *(_DWORD *)((char *)v29 + v32 + 32);
      if ( v19 >= 0 )
      {
        while ( 1 )
        {
          v21 = ((int)hModule + v19) >> 1;
          v16 = sub_10CA8E63((unsigned __int8 *)v29 + *(_DWORD *)&v20[4 * v21], v14, v21, a5);
          if ( v16 == -1 )
          {
            v19 = v21 - 1;
          }
          else if ( v16 )
          {
            if ( v16 == 1 )
              hModule = (HMODULE)(v21 + 1);
          }
          else
          {
            v44 = *(unsigned __int16 *)((char *)v29 + 2 * v21 + *(_DWORD *)((char *)v29 + v45 + 36));
            hModule = (HMODULE)(v19 + 1);
          }
          if ( (int)hModule > v19 )
            break;
          v14 = lpProcName;
          __rdtsc();
          v20 = v43;
        }
        v32 = v45;
        v8 = v44;
      }
    }
    if ( v8 < *(_DWORD *)((char *)v29 + v32 + 20) )
    {
      v35 = *(_DWORD *)((char *)v29 + 4 * v8 + *(_DWORD *)((char *)v29 + v32 + 28));
      if ( v35 )
        goto LABEL_15;
    }
    return 0;
  }
  v38 = (unsigned int)&lpProcName[-*(_DWORD *)((char *)hModule + v32 + 16)];
  if ( v38 >= *(_DWORD *)((char *)hModule + v32 + 20) )
    return 0;
  v35 = *(_DWORD *)((char *)hModule + 4 * v38 + *(_DWORD *)((char *)hModule + v32 + 28));
  if ( !v35 )
    return nullsub_7();
LABEL_15:
  if ( v35 < v32 )
    return nullsub_9(hModule);
  v13 = v32 + v42;
  if ( v35 >= v13 )
    return nullsub_9(hModule);
  v15 = (char *)v29 + v35;
  v33 = *((_BYTE *)v29 + v35);
  _ESI = v15;
  if ( !v33 )
    return 0;
  while ( v33 != 46 )
  {
    v33 = *++_ESI;
    if ( !v33 )
      return 0;
  }
  _ECX = _ESI - v15;
  if ( (unsigned int)(_ESI - v15) >= 0x104 )
    return 0;
  hModulea = 0;
  if ( _ECX )
  {
    _DL = v13 | 0xF6;
    __asm { rcl     dl, cl }
    v11 = (CHAR *)(LibFileName - v15);
    __asm { rcl     dl, 0FDh }
    do
    {
      v12 = *v15;
      if ( !v12 )
        break;
      v15[(_DWORD)v11] = v12;
      v31 = (char *)hModulea + 1;
      ++v15;
      hModulea = (HMODULE)((char *)hModulea + 1);
    }
    while ( (unsigned int)v31 < _ECX );
  }
  LibFileName[(_DWORD)hModulea] = 0;
  ModuleHandleA = GetModuleHandleA(LibFileName);
  if ( !ModuleHandleA )
  {
    ModuleHandleA = LoadLibraryA(LibFileName);
    if ( !ModuleHandleA )
      return 0;
  }
  if ( ModuleHandleA == v29 )
  {
    if ( a5 )
    {
      _EAX = LibFileName;
      __asm { rcr     esi, 0A7h }
      v27 = 0;
      __asm
      {
        rcl     eax, cl
        rcr     ah, 1Ah
      }
      do
      {
        v37 = LibFileName[v27 + lpProcName - (unsigned __int8 *)LibFileName] ^ (v27 + __ROL4__(1125323533, v27));
        LibFileName[v27] = v37;
        if ( !v37 )
          break;
        ++v27;
      }
      while ( v27 < 0x104 );
      GetProcAddress(v29, LibFileName);
      return nullsub_10(hModulea);
    }
    else
    {
      GetProcAddress(v29, (LPCSTR)lpProcName);
      return nullsub_8(hModulea);
    }
  }
  else if ( _ESI[1] == 35 )
  {
    v22 = _ESI[2];
    v23 = _ESI + 2;
    v24 = 0;
    if ( v22 )
    {
      do
      {
        ++v23;
        if ( (unsigned __int8)(v22 - 48) > 9u )
          break;
        v24 = (const CHAR *)(v22 + 10 * (_DWORD)v24 - 48);
        v22 = *v23;
      }
      while ( *v23 );
    }
    sub_108DEEB4(ModuleHandleA, v24, 0);
    return nullsub_11(hModulea);
  }
  else
  {
    return sub_108DEEB4(ModuleHandleA, _ESI + 1, 0);
  }
}
// 108DEEB4: could not find valid save-restore pair for ebx
// 108DEEB4: could not find valid save-restore pair for esi
// 10788BB1: using guessed type int nullsub_6(void);
// 107CD5BE: using guessed type int __cdecl nullsub_10(_DWORD);
// 107ED7AB: using guessed type int __cdecl nullsub_8(_DWORD);
// 1083E027: using guessed type int nullsub_7(void);
// 10CC618F: using guessed type int __cdecl nullsub_11(_DWORD);
// 10D13ECB: using guessed type int __cdecl nullsub_9(_DWORD);
// 108DEEB4: using guessed type CHAR LibFileName[260];

//----- (108E66DC) --------------------------------------------------------
int __usercall sub_108E66DC@<eax>(_BYTE *a1@<eax>, char *a2@<ecx>, __int16 a3@<bx>, int a4@<ebp>)
{
  char v4; // bl
  unsigned __int8 v5; // al
  char *v10; // esi
  char v11; // dl
  char v12; // al
  unsigned __int8 v16; // cl

  _BX = 2 * a3;
  HIBYTE(_BX) >>= (char)a2;
  __asm { rcl     bx, 0B9h }
  v10 = a2;
  v11 = 0;
  do
  {
    v12 = *v10;
    *(_BYTE *)(a4 - 1) = *a1;
    _CL = v11;
    ++v10;
    ++a1;
    v4 = v11 + __ROL4__(1125323533, v11);
    __asm { rcl     cl, 0AFh }
    v5 = v4 ^ v12;
    _CL = v5 - 65;
    ++v11;
    if ( _CL <= 0x19u )
    {
      v5 += 32;
      _BL = v11 ^ v4;
      __asm { rcl     bl, cl }
    }
    v16 = *(_BYTE *)(a4 - 1);
    if ( (unsigned __int8)(v16 - 65) <= 0x19u )
      v16 += 32;
  }
  while ( v5 && v5 == v16 );
  if ( v16 <= v5 )
    return nullsub_112();
  else
    return nullsub_113();
}
// 108428DF: using guessed type int nullsub_112(void);
// 10E6086F: using guessed type int nullsub_113(void);

//----- (10CA2D4B) --------------------------------------------------------
void sub_10CA2D4B()
{
  __asm
  {
    rcl     ebp, 0FDh
    retn
  }
}

//----- (10CA5B0A) --------------------------------------------------------
void __usercall sub_10CA5B0A(
        int _EAX@<eax>,
        int a2@<edx>,
        char _CL@<cl>,
        int _EBX@<ebx>,
        int a5@<edi>,
        int (**a6)(void)@<esi>)
{
  int v9; // ebx
  int (*v10)(void); // [esp-10h] [ebp-10h]
  int v11; // [esp-Ch] [ebp-Ch]

  --BYTE1(_EAX);
  LOBYTE(a2) = -(char)(a2 + 1);
  __asm { rcl     eax, cl }
  LOBYTE(_EBX) = a2 ^ _EBX;
  _BP = 0;
  v11 = _EBX;
  __asm
  {
    rcl     bh, cl
    rcl     bp, 0D9h
  }
  v9 = a2;
  for ( *(a6 - 1) = (int (*)(void))&a6[a2]; v9; --v9 )
    v10 = a6[v9];
  *(_DWORD *)*(a6 - 1) = (*a6)();
  __asm { jmp     edi }
}
// 10CC63F1: variable 'v10' is possibly undefined

//----- (10CA8E63) --------------------------------------------------------
int __usercall sub_10CA8E63@<eax>(unsigned __int8 *_EAX@<eax>, unsigned __int8 *_ECX@<ecx>, __int16 _SI@<si>, char a4)
{
  unsigned __int8 *v5; // edi
  unsigned __int8 *v6; // esi
  int v8; // edx
  unsigned __int8 v9; // cl
  unsigned __int8 v10; // al

  __asm { rcr     si, 0D9h }
  v5 = _EAX;
  v6 = _ECX;
  __asm { rcl     al, cl }
  v8 = 0;
  do
  {
    v9 = *v5;
    v10 = *v6++;
    ++v5;
    if ( a4 )
    {
      v10 ^= (_BYTE)v8 + (unsigned __int8)__ROL4__(1125323533, v8);
      ++v8;
    }
  }
  while ( v10 && v10 == v9 );
  if ( v9 <= v10 )
    return nullsub_5();
  else
    return -1;
}
// 108E47E3: using guessed type int nullsub_5(void);

//----- (10CD7B27) --------------------------------------------------------
int __usercall sub_10CD7B27@<eax>(int a1@<ebx>, int a2@<ebp>, int a3@<edi>, unsigned int *a4@<esi>)
{
  unsigned int v5; // kr00_4

  v5 = __readeflags();
  *a4 = v5;
  return ((int (*)(void))(_byteswap_ulong(_byteswap_ulong((a1 ^ *(_DWORD *)(a2 - 4)) - 1) ^ 0x77D775F1) + a3))();
}

//----- (10CD7C66) --------------------------------------------------------
void __usercall sub_10CD7C66(
        int _EAX@<eax>,
        int _EDX@<edx>,
        int a3@<ecx>,
        int a4@<ebp>,
        int _EDI@<edi>,
        int _ESI@<esi>,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26)
{
  unsigned int v26; // kr00_4
  int v29; // edi
  __int16 v30; // sp
  int v31; // edx
  unsigned int v32; // kr04_4
  _DWORD *v34; // eax
  int v35; // ebp
  int v36; // [esp-64h] [ebp-184h]
  _BYTE v37[64]; // [esp-60h] [ebp-180h] BYREF
  char v38; // [esp+0h] [ebp-120h] BYREF
  _BYTE v39[64]; // [esp+20h] [ebp-100h] BYREF
  _DWORD v40[11]; // [esp+E0h] [ebp-40h] BYREF
  _DWORD v41[5]; // [esp+10Ch] [ebp-14h] BYREF

  v41[4] = a3 + 1;
  v35 = a4 + 1;
  v41[2] = _EDX;
  __asm { arpl    ax, dx }
  v41[0] = v35 - 1;
  __asm { arpl    di, dx }
  v40[10] = v41;
  v40[8] = _EAX;
  v40[7] = _EAX;
  v31 = v30;
  v40[6] = _ESI;
  v40[5] = v35;
  __asm { arpl    ax, si }
  v32 = __readeflags();
  v40[4] = v32;
  _ECX = (__int16)_ESI + 1;
  BYTE1(v31) = __ROL1__(BYTE1(v31), _ECX);
  v34 = (_DWORD *)(_EAX + 1);
  BYTE1(_ECX) &= 0x11u;
  v40[3] = _ECX;
  v40[2] = _EDI;
  LOWORD(_ECX) = _ECX + 1;
  v40[1] = (char *)v34 + v31;
  BYTE1(v31) = (unsigned __int16)((_WORD)v34 + v31) >> 8 << _ECX;
  __asm { rcr     ch, cl }
  v40[0] = -276835694;
  LOBYTE(v31) = __OFADD__(1, (a26 + 1) ^ 0x284C5123);
  _SI = v31;
  __asm { arpl    bx, si }
  v34 = (_DWORD *)((char *)v34 - 1);
  *(_DWORD *)(2 * (_DWORD)v34) = *(_DWORD *)(2 * (_DWORD)v34);
  _disable();
  v29 = __ROR4__((char *)v34 + *v34, 3) + 1 + _EDI;
  if ( v40 <= (_DWORD *)&v38 )
  {
    v36 = v29;
    v26 = __readeflags();
    qmemcpy(v39, v37, sizeof(v39));
    __writeeflags(v26);
    v29 = v36;
  }
  __asm { retn }
}
// 10802D3A: variable 'v30' is possibly undefined

//----- (10E32BB8) --------------------------------------------------------
void __usercall sub_10E32BB8(char a1@<cl>, int _EBX@<ebx>, int a3@<edi>, unsigned int a4)
{
  int v7; // ebx

  __readeflags();
  _CL = a1 ^ 0xC2;
  LOBYTE(_EBX) = ~(_BYTE)_EBX;
  LOWORD(_EBX) = (__int16)_EBX >> 2;
  _EDI = -a3;
  __asm
  {
    rcr     di, 7Eh
    rcr     edi, 3Bh
    rcl     ebx, cl
  }
  v7 = __ROL4__((_byteswap_ulong(a4) ^ 0xA15315) + 1, 3);
  __asm { jmp     edi }
}

//----- (10E557A8) --------------------------------------------------------
void __usercall sub_10E557A8(__int16 a1@<di>, int a2)
{
  int v3; // ebx

  __readeflags();
  _DI = a1 & 0x9BC;
  __asm { rcl     di, 0D0h }
  v3 = __ROR4__(_byteswap_ulong(-a2) - 1232024735, 1) + 172310537;
  __asm { jmp     edi }
}

//----- (10E6ED14) --------------------------------------------------------
void sub_10E6ED14()
{
  ;
}

//----- (10E73280) --------------------------------------------------------
void sub_10E73280()
{
  __asm { jmp     esi }
}

// nfuncs=190 queued=29 decompiled=29 lumina nreq=0 worse=0 better=0
#error "There were 1 decompilation failure(s) on 29 function(s)"
